// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           25
// Async Callback (empty):               1
// Promise callbacks:                    3
// Total number of exported functions:  31

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    sovereign_forge
    (
        init => init
        upgrade => upgrade
        registerChainFactory => register_chain_factory
        registerTrustedToken => register_trusted_token
        deployPhaseOne => deploy_phase_one
        deployPhaseTwo => deploy_phase_two
        deployPhaseThree => deploy_phase_three
        deployPhaseFour => deploy_phase_four
        completeSetupPhase => complete_setup_phase
        getDeployedSovereignContracts => sovereign_deployed_contracts
        getTrustedTokens => trusted_tokens
        getSovereignSetupPhase => sovereign_setup_phase
        getChainFactoryAddress => chain_factories
        getDeployCost => deploy_cost
        getAllChainIds => chain_ids
        updateEsdtSafeConfig => update_esdt_safe_config
        updateSovereignConfig => update_sovereign_config
        setFee => set_fee
        removeFee => remove_fee
        addUsersToWhitelist => add_users_to_whitelist
        removeUsersFromWhitelist => remove_users_from_whitelist
        setTokenBurnMechanism => set_token_burn_mechanism
        setTokenLockMechanism => set_token_lock_mechanism
        updateDeployCost => update_deploy_cost
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        setup_phase => setup_phase
        register_deployed_contract => register_deployed_contract
        update_configs => update_configs
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
