[settings]
main = "main"

[contracts.main]
name = "pair-mock"

[contracts.full]
name = "pair-mock-full"
add-unlabelled = true
add-labels = ["pair-mock-external-view"]

[contracts.view]
name = "pair-mock-view"
external-view = true
add-unlabelled = false
add-labels = ["pair-mock-external-view"]

[[proxy]]
path = "src/pair_mock_proxy.rs"

[[proxy]]
path = "../token-handler/src/dummy_enshrine_proxy.rs"
