// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    sov_registrar
    (
        init => init
        upgrade => upgrade
        registerSetFee => register_set_fee
        registerRemoveFee => register_remove_fee
        registerDistributeFees => register_distribute_fees
        registerAddUsersToFeeWhitelist => register_add_users_to_fee_whitelist
        registerRemoveUsersFromFeeWhitelist => register_remove_users_from_fee_whitelist
        registerUpdateSovereignConfig => register_update_sovereign_config
        registerUpdateRegistrationStatus => register_update_registration_status
        registerUpdateEsdtSafeConfig => register_update_esdt_safe_config
        getTokenFee => token_fee
        getUsersWhitelist => users_whitelist
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
