// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    sov_registrar
    (
        init => init
        upgrade => upgrade
        setFee => set_fee
        removeFee => remove_fee
        distributeFees => distribute_fees
        addUsersToFeeWhitelist => add_users_to_fee_whitelist
        removeUsersFromFeeWhitelist => remove_users_from_fee_whitelist
        updateSovereignConfig => update_sovereign_config
        updateEsdtSafeConfig => update_esdt_safe_config
        getTokenFee => token_fee
        getUsersWhitelist => users_whitelist
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
