// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Promise callbacks:                    3
// Total number of exported functions:  18

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mvx_esdt_safe
    (
        init => init
        upgrade => upgrade
        updateConfiguration => update_configuration
        setFeeMarketAddress => set_fee_market_address
        setMaxBridgedAmount => set_max_bridged_amount
        deposit => deposit
        executeBridgeOps => execute_operations
        registerToken => register_token
        registerNativeToken => register_native_token
        getNativeToken => native_token
        getMaxBridgedAmount => max_bridged_amount
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        execute_callback => execute_callback
        issue_callback => issue_callback
        native_token_issue_callback => native_token_issue_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
