[package]
name = "esdt-safe-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.esdt-safe]
path = ".."

[dependencies.multiversx-sc-meta-lib]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "710ecc80fb2e909a3d564c9a586a48df82f53ebb"
version = "=0.53.2"
