// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           28
// Async Callback (empty):               1
// Promise callbacks:                    3
// Total number of exported functions:  34

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mvx_esdt_safe
    (
        init => init
        upgrade => upgrade
        updateEsdtSafeConfigSetupPhase => update_esdt_safe_config_during_setup_phase
        updateEsdtSafeConfig => update_esdt_safe_config
        setFeeMarketAddress => set_fee_market_address
        completeSetupPhase => complete_setup_phase
        blacklistDepositCaller => blacklist_deposit_caller
        removeDepositCallerFromBlacklist => remove_deposit_caller_from_blacklist
        deposit => deposit
        getDepositCallersBlacklist => deposit_callers_blacklist
        executeBridgeOps => execute_operations
        registerToken => register_sovereign_token
        registerNativeToken => register_native_token
        setTokenBurnMechanismSetupPhase => set_token_burn_mechanism_setup_phase
        setTokenBurnMechanism => set_token_burn_mechanism
        setTokenLockMechanismSetupPhase => set_token_lock_mechanism_setup_phase
        setTokenLockMechanism => set_token_lock_mechanism
        getDepositedTokensAmount => deposited_tokens_amount
        getSovToMvxTokenId => sovereign_to_multiversx_token_id_mapper
        getMvxToSovTokenId => multiversx_to_sovereign_token_id_mapper
        getSovEsdtTokenInfo => sovereign_to_multiversx_esdt_info_mapper
        getMvxEsdtTokenInfo => multiversx_to_sovereign_esdt_info_mapper
        getNativeToken => native_token
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
        execute => execute
        register_token => register_token
        native_token_issue_callback => native_token_issue_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
