// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           18
// Async Callback (empty):               1
// Promise callbacks:                    3
// Total number of exported functions:  24

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mvx_esdt_safe
    (
        init => init
        upgrade => upgrade
        updateEsdtSafeConfigSetupPhase => update_esdt_safe_config_during_setup_phase
        updateEsdtSafeConfig => update_esdt_safe_config
        setFeeMarketAddress => set_fee_market_address
        completeSetupPhase => complete_setup_phase
        deposit => deposit
        executeBridgeOps => execute_operations
        registerToken => register_token
        registerNativeToken => register_native_token
        setTokenBurnMechanism => set_token_burn_mechanism
        setTokenLockMechanism => set_token_lock_mechanism
        getSovToMvxTokenId => sovereign_to_multiversx_token_id_mapper
        getMvxToSovTokenId => multiversx_to_sovereign_token_id_mapper
        getSovEsdtTokenInfo => sovereign_to_multiversx_esdt_info_mapper
        getMvxEsdtTokenInfo => multiversx_to_sovereign_esdt_info_mapper
        getNativeToken => native_token
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        execute => execute
        issue_callback => issue_callback
        native_token_issue_callback => native_token_issue_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
