mvx_esdt_safe_address = "erd1qqqqqqqqqqqqqpgq8u06kjuq8hmf5kkced5ar4dgxrulp4d7a4sqsfzxks"
header_verfier_address = "erd1qqqqqqqqqqqqqpgqvjxhgxwh8fyzmr665k6arng0axwkna7ga4sqsr3luy"
fee_market_address = "erd1qqqqqqqqqqqqqpgqn6kcv0jhyhrc9fnqdz48zgx64cq99c7ua4sqcg0cg0"
testing_sc_address = "erd1qqqqqqqqqqqqqpgqv3qjssgf2kx0ymywg8ehe24sknhps3lna4sqzvjygn"
