mvx_esdt_safe_address = "erd1qqqqqqqqqqqqqpgqqhckc79l8pnw39fzxan5zptvpmx3xqqza4sqtlxs0j"
header_verfier_address = "erd1qqqqqqqqqqqqqpgqcy3kcmhq6dtdx26qtvyu37r4zfqv3sfpa4sqgnpk0n"
fee_market_address = "erd1qqqqqqqqqqqqqpgqm74agka9qlzffwzyqe68c57t2zz8jxjva4sqnn5cuv"
testing_sc_address = "erd1qqqqqqqqqqqqqpgq8702learxl37c39r5x22jc6w53w2mtzaa4sqej4md6"
