[package]
name = "forge-rust-interact"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[[bin]]
name = "forge-rust-interact"
path = "src/interactor_main.rs"

[lib]
path = "src/interact.rs"

[dependencies.sovereign-forge]
path = ".."

[dependencies.multiversx-sc-snippets]
version = "0.54.5"

[dependencies.multiversx-sc]
version = "0.54.5"

[dependencies.transaction]
path = "../../common/transaction"

[dependencies.proxies]
path = "../../common/proxies"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.6"

[features]
chain-simulator-tests = []

