[[bin]]
name = "forge-rust-interact"
path = "src/interactor_main.rs"

[package]
name = "forge-rust-interact"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/interact.rs"

[dependencies]
toml = "0.8.6"

[dependencies.sovereign-forge]
path = ".."

[dependencies.multiversx-sc-snippets]
version = "0.56.1"

[dependencies.multiversx-sc]
version = "0.56.1"

[dependencies.operation]
path = "../../common/operation"

[dependencies.proxies]
path = "../../common/proxies"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[features]
chain-simulator-tests = []
