contract_address = "erd1qqqqqqqqqqqqqpgqt5w9vlsdcmu5t5wvzdj8xnp42kqm4x3ud8ssrk9q8s"
config_address = "erd1qqqqqqqqqqqqqpgqn2ju3265cuh08uc3mesevpkjktggjhded8ssqa0spk"
factory_address = "erd1qqqqqqqqqqqqqpgqll6ncfgjppe7gns40vq7xuq6wsvkfk6kd8ss8ujx5r"
header_verifier_address = "erd1qqqqqqqqqqqqqpgquxv6eew4nzmcy0sr4r939p6wzcm0zkc8d8ssjspkj7"
