contract_address = "erd1qqqqqqqqqqqqqpgqt54uz2y2frvy7fqet479a6efarnyw3yud8ssj6kyuz"
config_address = "erd1qqqqqqqqqqqqqpgqd3sm30pzrsqs2y7ct6368tlt94d6xvl6d8ssqhckfm"
factory_address = "erd1qqqqqqqqqqqqqpgq9xqda668zt76c8tvfqe9t39g7pz0j9t2d8sss3w65z"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqlmtayq49qt94dj7gghagd7ap3d3htj76d8sszr0t7z"
esdt_safe_address = "erd1qqqqqqqqqqqqqpgqvxvmyp2fgr6qekksx8n6t8netkpweh28d8ssw9gwh8"
