contract_address = "erd1qqqqqqqqqqqqqpgqp7savykx0n380r5fykpfg629dumcqm6ud8ss2rkes5"
config_address = "erd1qqqqqqqqqqqqqpgq4f6lm4mppra83zrz5r68f8ysutx7xqlrd8ssu2a8gu"
factory_address = "erd1qqqqqqqqqqqqqpgq55shtd9738tvtcndca46utay5wfqm84sd8sskm267y"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqsl0phg7xmzhqmk768h9agrrscgm7qwudd8ssls3aq2"
