// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    sov_registrar
    (
        init => init
        upgrade => upgrade
        registerSetFee => register_set_fee
        registerRemoveFee => register_remove_fee
        registerDistributeFees => register_distribute_fees
        getTokenFee => token_fee
        getUsersWhitelist => users_whitelist
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
