// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        upgrade => upgrade
        stake => stake
        unStake => unstake
        getDelegationAddress => delegation_address
        getDelegatedValue => delegated_value
        unDelegateEpoch => undelegate_epoch
        getTotalEgldSupply => egld_token_supply
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
