// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback:                       1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        upgrade => upgrade
        registerDelegationContractAddress => register_delegation_address
        registerHeaderVerifierAddress => register_header_verifier_address
        registerBlsKeys => register_bls_keys
        stake => stake
        unStake => unstake
        getDelegationAddress => delegation_addresses
        getDelegatedValue => delegated_value
        unDelegateEpoch => undelegate_epoch
        getTotalEgldSupply => egld_token_supply
        getHeaderVerifierAddress => header_verifier_address
        getRegisteredBlsKeys => registered_bls_keys
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
