// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    chain_factory
    (
        init => init
        upgrade => upgrade
        deploySovereignChainConfigContract => deploy_sovereign_chain_config_contract
        deployHeaderVerifier => deploy_header_verifier
        setEsdtSafeAddressInHeaderVerifier => set_esdt_safe_address_in_header_verifier
        deployEnshrineEsdtSafe => deploy_enshrine_esdt_safe
        deployEsdtSafe => deploy_esdt_safe
        deployFeeMarket => deploy_fee_market
        completeSetupPhase => complete_setup_phase
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
