// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    chain_factory
    (
        init => init
        upgrade => upgrade
        deploySovereignChainConfigContract => deploy_sovereign_chain_config_contract
        addContractsToMap => add_contracts_to_map
        blacklistSovereignChainSc => blacklist_sovereign_chain_sc
        getContractsMap => contracts_map
        getDeployCost => deploy_cost
        slash => slash
        distributeSlashed => distribute_slashed
        setMinValidSigners => set_min_valid_signers
        addSigners => add_signers
        removeSigners => remove_signers
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
