// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    chain_factory
    (
        init => init
        upgrade => upgrade
        deploySovereignChainConfigContract => deploy_sovereign_chain_config_contract
        deployHeaderVerifier => deploy_header_verifier
        deployEsdtSafe => deploy_mvx_esdt_safe
        deployFeeMarket => deploy_fee_market
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
        updateEsdtSafeConfig => update_esdt_safe_config
        updateSovereignConfig => update_sovereign_config
        setFee => set_fee
        removeFee => remove_fee
        addUsersToWhitelistSetupPhase => add_users_to_whitelist
        removeUsersFromWhitelistSetupPhase => remove_users_from_whitelist
        completeSetupPhase => complete_setup_phase
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
