[package]
name = "from-sovereign-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.from-sovereign]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.56.0"
default-features = false
