// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    chain_factory
    (
        init => init
        upgrade => upgrade
        deploySovereignChainConfigContract => deploy_sovereign_chain_config_contract
        addContractsToMap => add_contracts_to_map
        deployHeaderVerifier => deploy_header_verifier
        deployCrossChainOperation => deploy_cross_chain_operation
        deployFeeMarket => deploy_fee_market
        deployTokenHandler => deploy_token_handler
        getContractsMap => contracts_map
        getDeployCost => deploy_cost
        getCurrentChainInfo => current_chain_info
        getAllChainIds => chain_ids
        slash => slash
        distributeSlashed => distribute_slashed
        setMinValidSigners => set_min_valid_signers
        addSigners => add_signers
        removeSigners => remove_signers
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
