// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    chain_config
    (
        init => init
        upgrade => upgrade
        updateSovereignConfigSetupPhase => update_sovereign_config_during_setup_phase
        updateSovereignConfig => update_sovereign_config
        completeSetupPhase => complete_setup_phase
        sovereignConfig => sovereign_config
        wasPreviouslySlashed => was_previously_slashed
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
