[[bin]]
name = "esdt-safe-interactor"
path = "src/esdt_safe_interactor_main.rs"

[package]
name = "esdt-safe-interactor"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/esdt_safe_interactor.rs"

[dependencies]
toml = "0.8.6"

[dependencies.esdt-safe]
path = ".."

[dependencies.operation]
path = "../../common/operation"

[dependencies.proxies]
path = "../../common/proxies"

[dependencies.tx-batch-module]
path = "../../common/tx-batch-module"

[dependencies.interactor]
path = "../../common/interactor"

[dependencies.fee-market]
path = "../../fee-market"

[dependencies.multiversx-sc-snippets]
version = "=0.55.0"

[dependencies.multiversx-sc]
version = "=0.55.0"

[dependencies.multiversx-sc-scenario]
version = "=0.55.0"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
