[package]
name = "rust-interact"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[[bin]]
name = "rust-interact"
path = "src/interactor_main.rs"

[dependencies.esdt-safe]
path = ".."

[dependencies.transaction]
path = "../../common/transaction"

[dependencies.tx-batch-module]
path = "../../common/tx-batch-module"

[dependencies.fee-market]
path = "../../fee-market"

[dependencies.multiversx-sc-snippets]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "710ecc80fb2e909a3d564c9a586a48df82f53ebb"
version = "=0.53.2"

[dependencies.multiversx-sc]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "710ecc80fb2e909a3d564c9a586a48df82f53ebb"
version = "=0.53.2"

[dependencies.multiversx-sc-scenario]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "710ecc80fb2e909a3d564c9a586a48df82f53ebb"
version = "=0.53.2"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.6"

# [workspace]

