contract_address = "erd1qqqqqqqqqqqqqpgqq8rrpwuqcsz9qrvzl3u0evfhsts536uurruqhpazdl"
fee_market_address = "erd1qqqqqqqqqqqqqpgqkr3uwzer9pswjwfemd4qrmhy8krvj7ysrruq7jqpxh"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqynssknta6hks8u6za0res0cjxu7pepeerruq2xjq6n"
testing_sc_address = "erd1qqqqqqqqqqqqqpgqku8sgx0d5t5esuhgkaxmv92qlkduzeryrruqtz2lf4"
