contract_address = "erd1qqqqqqqqqqqqqpgqgwpy5k5zt7ph3qd3kzywe6rdsl2lvtrjt7asdgwl7y"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqwwaflpw2gyn6q29ex9ajykhggwgyuyjzt7ashzg7z9"
fee_market_address = "erd1qqqqqqqqqqqqqpgqv5r87t76nh2ve48lh3m82drsywscvq5qt7asglafwx"
testing_sc_address = "erd1qqqqqqqqqqqqqpgq3p869qc4sf2752467jdnwvnak5tk4z3ct7asha9wzm"
