contract_address = "erd1qqqqqqqqqqqqqpgqkm0kcwasdlv03fc3r2t4n5mln8dpsf8nrruqy2k3ya"
fee_market_address = "erd1qqqqqqqqqqqqqpgq4rsu38s3jcmq4l53f0x552mjpdxh2jharruq4rxkqy"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqdf6w0tfcaly25ealg6cnljh5xhkvkyemrruqr7lg5n"
