contract_address = "erd1qqqqqqqqqqqqqpgqtq8807c3nvpfsmvhaxfa92fgfw5zmg4qt7as97n7kg"
fee_market_address = "erd1qqqqqqqqqqqqqpgqcfne2fs7xs9lf2wshyr3cc78mv6wrpwgt7asw3gaew"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgqaxq8dtgynumu824wnerjymrpfh4maquat7asqysu0t"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqg4wen7hg6yypu77ach6dm0g2hvs3pey8t7asc0a02t"
