contract_address = "erd1qqqqqqqqqqqqqpgqcnv2tuqkmllgltxmuv52mdvcuws83wsut7asdpagcv"
fee_market_address = "erd1qqqqqqqqqqqqqpgqcfne2fs7xs9lf2wshyr3cc78mv6wrpwgt7asw3gaew"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqg4wen7hg6yypu77ach6dm0g2hvs3pey8t7asc0a02t"
