contract_address = "erd1qqqqqqqqqqqqqpgqfaqhhqwn5en78zpxvhxtr0er832d75xzrruqmds7jw"
fee_market_address = "erd1qqqqqqqqqqqqqpgqrm67grf92zrvwjedw6v3gs00yfw0zgfxrruqqsr7v2"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgq3p9nnjjz4v6q3pp2gmlye955zzwmh6utrruqpa2h8j"
testing_sc_address = "erd1qqqqqqqqqqqqqpgqj6jmt3sdryetqsft7k8xydjmklc37tuvrruqerhnan"
