contract_address = "erd1qqqqqqqqqqqqqpgqrm4wzw736rkp8zn66rn4jn7wvq5mv9mgrruq7ljpjg"
fee_market_address = "erd1qqqqqqqqqqqqqpgqa8fczxmgzytpa0gepnglrwrjv6zeenc3rruqzxjhh6"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgq9dar9a3afukcuvhppathcgd9cmvpc06hrruqeul28l"
testing_sc_address = "erd1qqqqqqqqqqqqqpgqj6xx22q2xfsm3tts6gspqutd6hymlzc7rruq5rdvmy"
