contract_address = "erd1qqqqqqqqqqqqqpgq5njhhvv5ld6f6kj0wumlwzyghv8kz7g0rruqk2ssq0"
fee_market_address = "erd1qqqqqqqqqqqqqpgq7qzqdk2302jesxhl87hcmu2ewx87hke0rruqgg4srf"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqgf5x6ysk68wg3p78qrvw8c48rjct9x6lrruql8hfm3"
