contract_address = "erd1qqqqqqqqqqqqqpgqymk3fgkphwvs6q800rl8ldet6nfjufsvrruqkj36fe"
fee_market_address = "erd1qqqqqqqqqqqqqpgqf0s7t53nq560vkuv9ut2u02w8rnhs6wmrruqvvwrn6"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgq3j0qzmndhdz82d5wgcksgcxalv97fa60rruqhjkmxw"
testing_sc_address = "erd1qqqqqqqqqqqqqpgqy6t7krdeytjz7c404z0nxdy8r3phju7nrruqhwaqcl"
