contract_address = "erd1qqqqqqqqqqqqqpgqe9r8mmsyv53lzcpqczax3w6mkghfj4gjrruql6mjek"
fee_market_address = "erd1qqqqqqqqqqqqqpgqe6ervcr3gcnyhzqnctg0gc0qdsenl0a2rruqq3zqdx"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgq65rle2cmk9y5jy46n7ujl7nx56l4n5fyrruqfxkeka"
testing_sc_address = "erd1qqqqqqqqqqqqqpgq8hagwha7ld9cfzvvjwqh98hzn8aj23s5rruqtf580k"
