contract_address = "erd1qqqqqqqqqqqqqpgqq7uzqmfqj378rtw69crq9a457esa7pcerruqqfdkrg"
fee_market_address = "erd1qqqqqqqqqqqqqpgq09rk7w07ws6gwgg0xr60nxsmenv5kwjvrruqql0a9k"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgq5ysrr7d6yjp0skz2w0vgdxmv8f0zf7qyrruqck8qnk"
testing_sc_address = "erd1qqqqqqqqqqqqqpgqy23kdt7xt85xydk3ssv7rc0tngvx9zzvrruq3lh7w6"
