contract_address = "erd1qqqqqqqqqqqqqpgq5kw0e78d70sw3xqr3a3fuy563g57c8plrruq2ur0ph"
fee_market_address = "erd1qqqqqqqqqqqqqpgq3h3dfcgezfwu7057y7vqmt2c03q45de3rruqzlq8ez"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqwwfa27qh4ywfpfl6x4hksd5j00m7tpq2rruq99gmej"
