contract_address = "erd1qqqqqqqqqqqqqpgqqcvr4u6u7sc4a7jhfc0axfas2qfc9calrruqwf5trx"
fee_market_address = "erd1qqqqqqqqqqqqqpgqq7l3qdzzygjjjwsymawn86y3e3fla2ezrruqmm5a7c"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqmplcdd2wzy3j57skecmzgklcg9ewrzvprruqgjpfh9"
testing_sc_address = "erd1qqqqqqqqqqqqqpgqr22m5qs5n3u0u07vrjmcvejzeljdm7qkrruq9n022t"
