contract_address = "erd1qqqqqqqqqqqqqpgq77gcenfwx5alyfpcmy9j7qthuhs8yj6qrruqp4u4qt"
fee_market_address = "erd1qqqqqqqqqqqqqpgqxa4sjvpr00eyq9vnccw38pca5xa3y0j5rruqf0wxx0"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4sshr5wx4ch5gd8847dsavahytt732kut7as6z3mv6"
header_verifier_address = "erd1qqqqqqqqqqqqqpgq8t0pym95x4npnzcg9agkkf26ct6m7eqjrruq69536m"
