contract_address = "erd1qqqqqqqqqqqqqpgqr6m9gnreldnk7efzeanchpa5s84rl7cqt7ascj2q4m"
fee_market_address = "erd1qqqqqqqqqqqqqpgqzh0vtrpuc47dk05ytd7akms950utmljxt7as2k94hu"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq4zhxptkn7qmjvq6c2m03wg7wam4vp0ewt7as50a74x"
