[package]
name = "liquid-staking-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.liquid-staking]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.0"
default-features = false
