// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    header_verifier
    (
        init => init
        upgrade => upgrade
        registerBlsPubKeys => register_bls_pub_keys
        registerBridgeOps => register_bridge_operations
        changeValidatorSet => change_validator_set
        setEsdtSafeAddress => set_esdt_safe_address
        removeExecutedHash => remove_executed_hash
        lockOperationHash => lock_operation_hash
        updateSovereignConfig => update_sovereign_config
        updateEsdtSafeConfig => update_esdt_safe_config
        completeSetupPhase => complete_setup_phase
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
