// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           19
// Async Callback:                       1
// Total number of exported functions:  22

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    enshrine_esdt_safe
    (
        init => init
        upgrade => upgrade
        updateConfiguration => update_configuration
        setFeeMarketAddress => set_fee_market_address
        deposit => deposit
        executeBridgeOps => execute_operations
        registerNewTokenID => register_new_token_id
        addTokensToWhitelist => add_tokens_to_whitelist
        removeTokensFromWhitelist => remove_tokens_from_whitelist
        addTokensToBlacklist => add_tokens_to_blacklist
        removeTokensFromBlacklist => remove_tokens_from_blacklist
        getTokenWhitelist => token_whitelist
        getTokenBlacklist => token_blacklist
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        getSovToMvxTokenId => sovereign_to_multiversx_token_id_mapper
        getMvxToSovTokenId => multiversx_to_sovereign_token_id_mapper
        getSovEsdtTokenInfo => sovereign_to_multiversx_esdt_info_mapper
        getMvxEsdtTokenInfo => multiversx_to_sovereign_esdt_info_mapper
        getNativeToken => native_token
    )
}

multiversx_sc_wasm_adapter::async_callback! { enshrine_esdt_safe }
