// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    sov_fee_market
    (
        init => init
        upgrade => upgrade
        addUsersToWhitelist => add_users_to_whitelist
        removeUsersFromWhitelist => remove_users_from_whitelist
        getTokenFee => token_fee
        getUsersWhitelist => users_whitelist
        distributeFees => distribute_fees
        removeFee => remove_fee
        setFee => set_fee
        subtractFee => subtract_fee
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
