// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    testing_sc
    (
        init => init
        upgrade => upgrade
        hello => hello
        view_storage => view_storage
        view_storage_async => view_storage_async
        view_storage_sync => view_storage_sync
        send_tokens => send_tokens
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
