[settings]
main = "main"

[contracts.main]
name = "to-sovereign"

[contracts.full]
name = "to-sovereign-full"
add-unlabelled = true
add-labels = ["to-sovereign-external-view"]

[contracts.view]
name = "to-sovereign-view"
external-view = true
add-unlabelled = false
add-labels = ["to-sovereign-external-view"]

[[proxy]]
path = "../common/proxies/src/from_sovereign_proxy.rs"
