// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ChainConfigContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ChainConfigContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ChainConfigContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ChainConfigContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct ChainConfigContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ChainConfigContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<OptionalValue<structs::configs::SovereignConfig<Env::Api>>>,
    >(
        self,
        opt_config: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&opt_config)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ChainConfigContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ChainConfigContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn complete_setup_phase(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("completeSetupPhase")
            .original_result()
    }

    pub fn register<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        new_bls_key: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("register")
            .argument(&new_bls_key)
            .original_result()
    }

    pub fn unregister<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        bls_key: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("unregister")
            .argument(&bls_key)
            .original_result()
    }

    pub fn sovereign_config(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, structs::configs::SovereignConfig<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("sovereignConfig")
            .original_result()
    }

    pub fn bls_key_to_id_mapper<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        bls_key: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("blsKeyToId")
            .argument(&bls_key)
            .original_result()
    }

    pub fn validator_info<
        Arg0: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, structs::ValidatorInfo<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("validator_info")
            .argument(&id)
            .original_result()
    }

    pub fn bls_keys_map(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<BigUint<Env::Api>, ManagedBuffer<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("blsKeysMap")
            .original_result()
    }

    pub fn was_previously_slashed<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        validator: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("wasPreviouslySlashed")
            .argument(&validator)
            .original_result()
    }

    pub fn update_sovereign_config_during_setup_phase<
        Arg0: ProxyArg<structs::configs::SovereignConfig<Env::Api>>,
    >(
        self,
        new_config: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateSovereignConfigSetupPhase")
            .argument(&new_config)
            .original_result()
    }

    pub fn update_sovereign_config<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<structs::configs::SovereignConfig<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        new_config: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateSovereignConfig")
            .argument(&hash_of_hashes)
            .argument(&new_config)
            .original_result()
    }

    pub fn update_registration_status<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u8>,
    >(
        self,
        hash_of_hashes: Arg0,
        registration_status: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateRegistrationStatus")
            .argument(&hash_of_hashes)
            .argument(&registration_status)
            .original_result()
    }
}
