// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct HeaderverifierProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for HeaderverifierProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = HeaderverifierProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        HeaderverifierProxyMethods { wrapped_tx: tx }
    }
}

pub struct HeaderverifierProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> HeaderverifierProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<MultiValueEncoded<Env::Api, structs::forge::ContractInfo<Env::Api>>>,
    >(
        self,
        sovereign_contracts: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&sovereign_contracts)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> HeaderverifierProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> HeaderverifierProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn complete_setup_phase(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("completeSetupPhase")
            .original_result()
    }

    pub fn operation_hash_status<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        operation_hash: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, structs::OperationHashStatus> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("operationHashStatus")
            .argument(&hash_of_hashes)
            .argument(&operation_hash)
            .original_result()
    }

    pub fn register_bridge_operations<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<MultiValueEncoded<Env::Api, ManagedBuffer<Env::Api>>>,
    >(
        self,
        signature: Arg0,
        hash_of_hashes: Arg1,
        pub_keys_bitmap: Arg2,
        epoch: Arg3,
        operations_hashes: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerBridgeOps")
            .argument(&signature)
            .argument(&hash_of_hashes)
            .argument(&pub_keys_bitmap)
            .argument(&epoch)
            .argument(&operations_hashes)
            .original_result()
    }

    pub fn change_validator_set<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<u64>,
        Arg5: ProxyArg<MultiValueEncoded<Env::Api, BigUint<Env::Api>>>,
    >(
        self,
        signature: Arg0,
        hash_of_hashes: Arg1,
        operation_hash: Arg2,
        pub_keys_bitmap: Arg3,
        epoch: Arg4,
        pub_keys_id: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("changeValidatorSet")
            .argument(&signature)
            .argument(&hash_of_hashes)
            .argument(&operation_hash)
            .argument(&pub_keys_bitmap)
            .argument(&epoch)
            .argument(&pub_keys_id)
            .original_result()
    }

    pub fn remove_executed_hash<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        operation_hash: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<ManagedBuffer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeExecutedHash")
            .argument(&hash_of_hashes)
            .argument(&operation_hash)
            .original_result()
    }

    pub fn lock_operation_hash<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        hash_of_hashes: Arg0,
        operation_hash: Arg1,
        operation_nonce: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<ManagedBuffer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("lockOperationHash")
            .argument(&hash_of_hashes)
            .argument(&operation_hash)
            .argument(&operation_nonce)
            .original_result()
    }
}
