// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct MvxFeeMarketProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for MvxFeeMarketProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = MvxFeeMarketProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        MvxFeeMarketProxyMethods { wrapped_tx: tx }
    }
}

pub struct MvxFeeMarketProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> MvxFeeMarketProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<Option<structs::fee::FeeStruct<Env::Api>>>,
    >(
        self,
        esdt_safe_address: Arg0,
        fee: Arg1,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&esdt_safe_address)
            .argument(&fee)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> MvxFeeMarketProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> MvxFeeMarketProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn complete_setup_phase(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("completeSetupPhase")
            .original_result()
    }

    pub fn distribute_fees<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<structs::fee::DistributeFeesOperation<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        operation: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("distributeFees")
            .argument(&hash_of_hashes)
            .argument(&operation)
            .original_result()
    }

    pub fn remove_fee_during_setup_phase<
        Arg0: ProxyArg<EgldOrEsdtTokenIdentifier<Env::Api>>,
    >(
        self,
        base_token: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeFeeDuringSetupPhase")
            .argument(&base_token)
            .original_result()
    }

    pub fn remove_fee<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<EgldOrEsdtTokenIdentifier<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        token_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeFee")
            .argument(&hash_of_hashes)
            .argument(&token_id)
            .original_result()
    }

    pub fn set_fee_during_setup_phase<
        Arg0: ProxyArg<structs::fee::FeeStruct<Env::Api>>,
    >(
        self,
        fee_struct: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFeeDuringSetupPhase")
            .argument(&fee_struct)
            .original_result()
    }

    pub fn set_fee<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<structs::fee::FeeStruct<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        fee_struct: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFee")
            .argument(&hash_of_hashes)
            .argument(&fee_struct)
            .original_result()
    }

    pub fn token_fee<
        Arg0: ProxyArg<EgldOrEsdtTokenIdentifier<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, structs::fee::FeeType<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTokenFee")
            .argument(&token_id)
            .original_result()
    }

    pub fn users_whitelist(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, ManagedAddress<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUsersWhitelist")
            .original_result()
    }

    pub fn subtract_fee<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<usize>,
        Arg2: ProxyArg<OptionalValue<u64>>,
    >(
        self,
        original_caller: Arg0,
        total_transfers: Arg1,
        opt_gas_limit: Arg2,
    ) -> TxTypedCall<Env, From, To, (), Gas, structs::fee::FinalPayment<Env::Api>> {
        self.wrapped_tx
            .raw_call("subtractFee")
            .argument(&original_caller)
            .argument(&total_transfers)
            .argument(&opt_gas_limit)
            .original_result()
    }

    pub fn add_users_to_whitelist_during_setup_phase<
        Arg0: ProxyArg<MultiValueEncoded<Env::Api, ManagedAddress<Env::Api>>>,
    >(
        self,
        users: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addUsersToWhitelistSetupPhase")
            .argument(&users)
            .original_result()
    }

    pub fn add_users_to_whitelist<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<structs::fee::AddUsersToWhitelistOperation<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        operation: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addUsersToWhitelist")
            .argument(&hash_of_hashes)
            .argument(&operation)
            .original_result()
    }

    pub fn remove_users_from_whitelist_during_setup_phase<
        Arg0: ProxyArg<MultiValueEncoded<Env::Api, ManagedAddress<Env::Api>>>,
    >(
        self,
        users: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeUsersFromWhitelistSetupPhase")
            .argument(&users)
            .original_result()
    }

    pub fn remove_users_from_whitelist<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<structs::fee::RemoveUsersFromWhitelistOperation<Env::Api>>,
    >(
        self,
        hash_of_hashes: Arg0,
        operation: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeUsersFromWhitelist")
            .argument(&hash_of_hashes)
            .argument(&operation)
            .original_result()
    }
}
