// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    fee_market
    (
        init => init
        upgrade => upgrade
        completeSetupPhase => complete_setup_phase
        removeFeeDuringSetupPhase => remove_fee_during_setup_phase
        removeFee => remove_fee
        setFeeDuringSetupPhase => set_fee_during_setup_phase
        setFee => set_fee
        getTokenFee => token_fee
        subtractFee => subtract_fee
        distributeFees => distribute_fees
        getUsersWhitelist => users_whitelist
        addUsersToWhitelist => add_users_to_whitelist
        removeUsersFromWhitelist => remove_users_from_whitelist
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
