[package]
name = "rust-interact-esdt-safe"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[[bin]]
name = "rust-interact-esdt-safe"
path = "src/interactor_main.rs"

[dependencies.enshrine-esdt-safe]
path = ".."

[dependencies.transaction]
path = "../../common/transaction"

[dependencies.tx-batch-module]
path = "../../common/tx-batch-module"

[dependencies.max-bridged-amount-module]
path = "../../common/max-bridged-amount-module"

[dependencies.setup-phase]
path = "../../common/setup-phase"

[dependencies.token-whitelist]
path = "../../common/token-whitelist"

[dependencies.utils]
path = "../../common/utils"

[dependencies.fee-market]
path = "../../fee-market"

[dependencies.header-verifier]
path = "../../header-verifier"

[dependencies.token-handler]
path = "../../token-handler"

[dependencies.proxies]
path = "../../common/proxies"

[dependencies.multiversx-sc-snippets]
version = "=0.54.4"

[dependencies.multiversx-sc]
version = "=0.54.4"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.6"

# uncomment when using chain simulator
# [features]
# chain-simulator-tests = []

