contract_address = "erd1qqqqqqqqqqqqqpgqwt234fqv6fw6sqetxl576pnn9ghv440qt7as5f3ewp"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqq83sadqyln9mlydwx87yznfz8rnduvkat7asgpej29"
fee_market_address = "erd1qqqqqqqqqqqqqpgq87tt5syaur3sw60x0y3klx28kzukreh7t7as3gx35g"
token_handler_address = "erd1qqqqqqqqqqqqqpgqpxj7fummz42wmc4fqym8x3tkkalenadut7asd2smmr"
price_aggregator_address = "erd1qqqqqqqqqqqqqpgq8ydr99ax62mj07s9ujpvzaqr05jvd0j6t7as0f7ndp"
