contract_address = "erd1qqqqqqqqqqqqqpgqv9hjetsqgz3smzv9hjd8sgp5sl5r0mm7t7as8gpl7v"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqq83sadqyln9mlydwx87yznfz8rnduvkat7asgpej29"
fee_market_address = "erd1qqqqqqqqqqqqqpgqyztpp6zsdygld3sjcrrsdnjmduqrlkn2t7ases8slc"
token_handler_address = "erd1qqqqqqqqqqqqqpgq9n7uw2dauhhwd7xqqvt7x7ahkpswnhstt7asdr8ejx"
