contract_address = "erd1qqqqqqqqqqqqqpgqctznxprpl8tv3uffchgn8wnctsc3hnl0t7asr50cgt"
header_verifier_address = "erd1qqqqqqqqqqqqqpgqq83sadqyln9mlydwx87yznfz8rnduvkat7asgpej29"
fee_market_address = "erd1qqqqqqqqqqqqqpgqyztpp6zsdygld3sjcrrsdnjmduqrlkn2t7ases8slc"
token_handler_address = "erd1qqqqqqqqqqqqqpgqqy7n9atn72cng32q70f6n9wyfwslpt4ct7asjvq63e"
