// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    to_sovereign
    (
        init => init
        upgrade => upgrade
        setFeeMarketAddress => set_fee_market_address
        setHeaderVerifierAddress => set_header_verifier_address
        deposit => deposit
        executeBridgeOps => execute_operations
        registerToken => register_token
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        setMaxBridgedAmount => set_max_bridged_amount
        getMaxBridgedAmount => max_bridged_amount
        execute => execute
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
