// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Promise callbacks:                    3
// Total number of exported functions:  23

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        upgrade => upgrade
        registerDelegationContractAddress => register_delegation_address
        registerHeaderVerifierAddress => register_header_verifier_address
        registerBlsKeys => register_bls_keys
        stake => stake
        unStake => unstake
        claimRewardsFromDelegation => claim_rewards_from_delegation
        slashValidator => slash_validator
        lockForSovereignChain => lock_for_sovereign_chain
        claim_rewards => claim_rewards
        getDelegationAddress => delegation_addresses
        getDelegatedValue => delegated_value
        unDelegateEpoch => undelegate_epoch
        getTotalEgldSupply => egld_token_supply
        getHeaderVerifierAddress => header_verifier_address
        getRegisteredBlsKeys => registered_bls_keys
        validatorBlsKeyMap => validator_bls_key_address_map
        lockedSupply => locked_supply
        stake_callback => stake_callback
        unstake_callback => unstake_callback
        claim_rewards_from_delegation_cb => claim_rewards_from_delegation_cb
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
