[package]
name = "utils"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.operation]
path = "../operation"

[dependencies.multiversx-sc]
version = "=0.56.0"
