[package]
name = "utils"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.bls-signature]
path = "../bls-signature"

[dependencies.multiversx-sc]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "710ecc80fb2e909a3d564c9a586a48df82f53ebb"
version = "=0.53.2"
features = ["esdt-token-payment-legacy-decode"]
