[settings]
main = "main"

[contracts.main]
name = "mvx-esdt-safe"

[contracts.full]
name = "mvx-esdt-safe-full"
add-unlabelled = true
add-labels = ["mvx-esdt-safe-external-view"]

[contracts.view]
name = "mvx-esdt-safe-view"
external-view = true
add-unlabelled = false
add-labels = ["mvx-esdt-safe-external-view"]

[[proxy]]
path = "../common/proxies/src/mvx_esdt_safe_proxy.rs"
