name: On pull request, build contracts

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v3.2.0
    with:
      image_tag: v8.0.0

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo tests
        run: cargo test --features chain-simulator-tests
